export default {
  'app.title.home': 'Online China Yiwu Hardware & Electrical Appliances Trade Fair',
  'app.title.mine': 'Mine',
  'app.footer.menu1': 'Home page',
  'app.footer.menu2': 'Purchasers',
  'app.footer.menu3': 'Demand',
  'app.footer.menu4': 'Mine',
  'app.home.menus1': 'My information',
  'app.home.menus2': 'Service exhibitors',
  'app.home.menus3': 'Events',
  'app.home.menus4': 'My Live video',
  'app.home.menus5': 'my reservation',
  'app.home.menus6': 'My message',
  'app.home.switchMenu1': 'Match to buyers',
  'app.home.switchMenu2': 'Match to demands',
  'app.mine.view': 'View',
  'app.mine.menu1': 'My reservation',
  'app.mine.menu2': 'My schedule',
  'app.mine.menu3': 'My product',
  'app.mine.menu4': 'My message',
  'app.mine.menu5': 'My Live video',
  'app.mine.menu6': 'Contact service',
  'app.mine.menu7': '已报名的活动',
  'app.mine.repass': 'Modify password',
  'app.mine.exit': 'Exit login',
  'app.activity.top': 'Trade matching',
  'app.activity.activity': 'No activity',
  'app.activity.top2': 'My reservation',
  'app.activity.btn1': 'My immediately',
  'app.activity.btn2': 'To make immediately',
  'app.activity.time': 'Time of the activity',
  'app.activity.roomNum': 'Number of conference rooms',
  'app.activity.taking': 'Negotiation duration(Minute)',
  'app.activity.rule': 'Rules',
  'app.activity.back': 'Return',
  'app.activity.confirm': 'Confirme',
  'app.activity.city': 'Nationality',
  'app.activity.kind': 'Product category',
  'app.activity.name': 'product name',
  'app.activity.num': 'Quantity',
  'app.activity.price': 'Price range',
  'app.activity.texture': 'Material properties',
  'app.activity.status1': 'Enter the conference',
  'app.activity.status2': "Haven't started",
  'app.activity.hint': 'No reservation',
  'app.mine.oldpwd': 'Original password',
  'app.mine.placoldpwd': 'Please enter the original password',
  'app.mine.newpwd': 'New password',
  'app.mine.placnewpwd': 'Please enter a new password',
  'app.mine.confirmpwd': 'Confirm password',
  'app.mine.placconfirmpwd': 'Please confirm the password',
  'app.mine.submit': 'Submit',
  'app.title.msg':'My message',
  'app.home.zedition1':'Confirmed',
  'app.home.zedition2':'TBC',
  'app.home.zedition3':'Refused',
  'app.home.zedition4':'Cancelled',
  'app.home.zedition5':'My invitation',
  'app.home.zedition6':'Invitation received',
  'app.home.zedition7':'Conference countdown',
  'app.home.zedition8':'expired',
  'app.home.zedition9':'Appointment theme',
  'app.home.zedition10':'Appointmenttime',
  'app.home.zedition11':'Time to initiate appointment',
  'app.home.zedition12':'Remarks',
  'app.home.zedition13':'Contacts',
  'app.home.zedition14':'Cancel reservation;',
  'app.home.zedition15':'Initiate appointment again',
  'app.home.zedition16':'Confirm',
  'app.home.zedition17':'Refuse',
  'app.home.zedition18':'Remind each other',
  'app.home.zedition19':'Refused',
  
  'app.title.addpro':'Add product',
  'app.title.editpro':'Edit product',
  'app.home.viewmore': 'View more',
  'app.home.loading': 'loading',
  'app.home.publishdemand': 'Published demand',
  'app.purchaser.title': 'Match to buyers',
  'app.demand.title':'Demand detail',
  'app.info.photo':'Photo upload',
  'app.info.shoot':'Shoot upload',
  'app.info.album':'Album selection',
  'app.im.send':'send',
  'app.im.system':'System messages',
  'app.im.shoot':'shoot',
  'app.im.picture':'photo',

  'app.nav.buyers':'Buyer List',
  'app.nav.demand':'Demand list',
  'app.nav.mine':'My Accounts',
  'app.nav.home':'闻信上海展现场直播平台',
  'app.nav.myinformation':'小瓜云展',
  'app.nav.looknav':'Visitor Guide',
  'app.nav.liveRelease':'New stream',

  "展馆号":"hallNumber",
  "展位号":"boothNumber",
};