export default {
  'app.company.kind': 'Nature of business',
  'app.intrest.kind': 'Product category of interest',
  'app.purchase.product.name': 'Name of purchasers',
  'app.purchase.product.num': 'Quantity',
  'app.purchase.product.priceRang': 'Price range',
  'app.purchase.product.properties': 'Material properties',
  'app.purchase.product.Industr': 'Industr',
  'app.purchase.product.detail': 'View exhibitors',
  'app.purchase.product.kind': 'Product category',
  'app.search.placeholder': 'Please enter the buyer\'s name',
  'app.search.filter': 'Select',
  'com.label.pic': 'Image',
  'app.btn.editInfo': 'Edit Profile',
  'app.meinfo.room.roomNum': 'Hall no',
  'app.meinfo.room.doorNum': 'Booth number',
  'app.meinfo.room.link': 'website',
  'app.meinfo.room.productType': 'Product category',
  'app.company.logo': 'Company image',
  'app.liveVideo': 'Live video',
  'app.company.introll':'Company Profile',
  'app.btn.delete': 'Delete',
  'app.btn.edit': 'Edit',
  'app.btn.ZHName': 'Product name (Chinese)',
  'app.btn.ENName': 'Product name (English)：',
  'app.btn.img': 'Product image',
  'app.btn.ZHIntroller': 'Product introduction (Chinese)',
  'app.btn.ENIntroller': 'Product introduction (English)',
  'app.btn.coverImg': 'Set to cover',
  'app.btn.cancel': 'Cancel',
  'app.btn.save': 'Save',
  'app.live.label.startTime': 'Start time',
  'app.live.label.endTime': 'End time',
  'app.live.label.duration': 'Duration',
  'app.live.label.liveStatus': 'Video status',
  'app.live.label.judgeStatus': 'Audit status',
  'app.live.label.num': 'Cumulative number of viewers',
  'app.live.label.conversionOfInvitaion': 'Conversion of invitation ',
  'app.live.label.sure': 'Confirmed',
  'app.live.label.waitSure': 'TBC',
  'app.live.label.reject': 'Rejected',
  'app.live.label.cancel': 'cancelled',
  'app.info.zhname': 'Company name(chinese)',
  'app.info.enname': 'Company name(English)',
  'app.info.no': 'Booth personnel',
  'app.info.sitno': 'Booth number',
  'app.info.img': 'Company image',
  'app.info.video': 'Promotional video',
  'app.info.ZHIntroller': 'Company Profile',
  'app.info.ENIntroller': 'English introduction',
  'app.info.remove': 'remove',
  'app.info.upload': 'upload',
  'app.live.btnstart':'Publish Live video',
  'app.live.theme':'Live video theme',
  'app.live.theme.placeholder':'Input Live video theme',
  'app.live.poster':'Add cover',
  'app.live.btn.start':'Start',
  'app.live.room.yuyue':'Appointments I received',
  'app.live.room.num':'Number',
  'app.live.room.duration':'Live time',
  'app.btn.contact':'Invite immediately',
  'app.title.myinvitation':'Appointments I received',
  'app.connect.label.invitaionSoon': 'Invite immediately',
  'app.invitaion.dialog.theme':'Appointment theme',
  'app.invitaion.dialog.theme.placeholder':'Please enter appointment subject',
  'app.invitaion.dialog.date':'Date',
  'app.invitaion.dialog.date.placeholder':'Selection date',
  'app.invitaion.dialog.time.start':'Start time',
  'app.invitaion.dialog.time.placeholder':'Selection time',
  'app.invitaion.dialog.time.end':'End time',
  'app.invitaion.dialog.msg':'Leaving a message',
  'app.invitaion.dialog.msg.placeholder':'Please enter the message content',
  'app.btn.sure':'Sure',
  'app.btn.cancel':'Cancel',
  'app.info.choosed':'choosed',
  'app.info.end': 'End',
  'app.pop.title.exitlive': 'Confirm to end the live broadcast?',
}