export default {
  'app.title.home': '小瓜云展',
   'app.title.mine': '我的',
  'app.footer.menu1': '首页',
  'app.footer.menu2': '采购商',
  'app.footer.menu3': '需求',
  'app.footer.menu4': '我的',
  'app.home.menus1': '我的资料',
  'app.home.menus2': '展商服务',
  'app.home.menus3': '配套活动',
  'app.home.menus4': '我的直播',
  'app.home.menus5': '我的预约',
  'app.home.menus6': '我的消息',
  'app.home.switchMenu1': '匹配采购商',
  'app.home.switchMenu2': '匹配需求',
  'app.mine.view': '查看',
  'app.mine.menu1': '我的预约',
  'app.mine.menu2': '我的日程',
  'app.mine.menu3': '我的产品',
  'app.mine.menu4': '我的消息',
  'app.mine.menu5': '我的直播',
  'app.mine.menu6': '联系客服',
  'app.mine.menu7': '已报名的活动',
  'app.mine.repass': '修改密码',
  'app.mine.exit': '退出登录',
  'app.activity.top': '商贸配对活动',
  'app.activity.activity': '暂无活动',
  'app.activity.top2': '我的预约',
  'app.activity.btn1': '我的预约',
  'app.activity.btn2': '立即预约',
  
  'app.activity.time': '活动时间',
  'app.activity.roomNum': '会议房间数量',
  'app.activity.taking': '洽谈时长(分钟)',
  
  
  'app.activity.rule': '活动规则',
  'app.activity.back': '返回上一页',
  'app.activity.confirm': '确定',
  'app.activity.city': '国籍',
  'app.activity.kind': '产品类别',
  'app.activity.name': '采购商品名称',
  'app.activity.num': '数量',
  'app.activity.price': '价格幅度',
  'app.activity.texture': '材质/规格',
  'app.activity.status1': '进入会议',
  'app.activity.status2': '未开始',
  'app.activity.hint': '暂无预约',
  
  'app.mine.oldpwd': '原密码',
  'app.mine.placoldpwd': '请输入原密码',
  'app.mine.newpwd': '新密码',
  'app.mine.placnewpwd': '请输入新密码',
  'app.mine.confirmpwd': '确认密码',
  'app.mine.placconfirmpwd': '请确认密码',
  'app.mine.submit': '确定',
  'app.title.msg':'我的消息',
  'app.home.zedition1':'已确认',
  'app.home.zedition2':'待确认',
  'app.home.zedition3':'已拒绝',
  'app.home.zedition4':'已取消',
  'app.home.zedition5':'我发起的预约',
  'app.home.zedition6':'我收到的预约',
  'app.home.zedition7':'会议开启倒计时',
  'app.home.zedition8':'已过期',
  'app.home.zedition9':'预约主题',
  'app.home.zedition10':'邀约时间',
  'app.home.zedition11':'发起时间',
  'app.home.zedition12':'备注留言',
  'app.home.zedition13':'联系人',
  'app.home.zedition14':'取消预约',
  'app.home.zedition15':'再次发起预约',
  'app.home.zedition16':'确认',
  'app.home.zedition17':'拒绝',
  'app.home.zedition18':'提醒对方',
  'app.home.zedition19':'已拒绝',
  'app.title.addpro':'新增产品',
  'app.title.editpro':'编辑产品',
  'app.home.viewmore': '查看更多',
  'app.home.loading': '正在加载',
  'app.home.publishdemand': '发布需求',
  'app.purchaser.title': '匹配采购商',
  'app.demand.title':'需求详情',
  'app.info.photo':'拍照上传',
  'app.info.shoot':'拍摄上传',
  'app.info.album':'相册选取',
  'app.im.send':'发送',
  'app.im.system':'系统消息',
  'app.im.shoot':'拍摄',
  'app.im.picture':'图片',


  'app.nav.buyers':'观众列表',
  'app.nav.demand':'需求列表',
  'app.nav.mine':'个人中心',
  'app.nav.home':'闻信上海展现场直播平台',
  'app.nav.myinformation':'义乌五金展在线平台',
};