export default {
  'app.company.kind': '业务性质',
  'app.intrest.kind': '感兴趣的产品类型',
  'app.purchase.product.name': '采购商品名称',
  'app.purchase.product.num': '数量',
  'app.purchase.product.priceRang': '价格幅度',
  'app.purchase.product.properties': '材质/规格',
  'app.purchase.product.Industr': '所属行业',
  'app.purchase.product.detail': '查看采购商',
  'app.purchase.product.kind': '采购商品类',
  'app.search.placeholder': '请输入采购商名称',
  'app.search.filter': '筛选',
  'com.label.pic': '照片',
  'app.btn.editInfo': '编辑资料',
  'app.meinfo.room.roomNum': '展馆号',
  'app.meinfo.room.doorNum': '展位号',
  'app.meinfo.room.link': '网址',
  'app.meinfo.room.productType': '产品类型',
  'app.company.logo': '公司图片',
  'app.liveVideo': '视频',
  'app.company.introll':'公司介绍',
  'app.btn.delete': '删除',
  'app.btn.edit': '编辑',
  'app.btn.ZHName': '产品中文名称',
  'app.btn.ENName': '产品英文名称',
  'app.btn.img': '产品图片',
  'app.btn.ZHIntroller': '产品中文介绍',
  'app.btn.ENIntroller': '产品英文介绍',
  'app.btn.coverImg': '设为封面',
  'app.btn.cancel': '取消',
  'app.btn.save': '保存',
  'app.live.label.startTime': '开始时间',
  'app.live.label.endTime': '结束时间',
  'app.live.label.duration': '时长',
  'app.live.label.liveStatus': '直播状态',
  'app.live.label.judgeStatus': '审核状态',
  'app.live.label.num': '累计观看人数',
  'app.live.label.conversionOfInvitaion': '转化预约数',
  'app.live.label.sure': '已确认',
  'app.live.label.waitSure': '待确认',
  'app.live.label.reject': '已拒绝',
  'app.live.label.cancel': '已取消',
  'app.info.zhname': '公司名称',
  'app.info.enname': '公司英文名称',
  'app.info.no': '展馆号',
  'app.info.sitno': '展位号',
  'app.info.img': '公司图片',
  'app.info.video': '宣传视频',
  'app.info.ZHIntroller': '公司中文介绍',
  'app.info.ENIntroller': '公司英文介绍',
  'app.info.remove': '清除',
  'app.info.upload': '上传',
  'app.live.btnstart':'发布直播',
  'app.live.theme':'直播主题',
  'app.live.theme.placeholder':'请输入直播主题',
  'app.live.poster':'添加封面',
  'app.live.btn.start':'开始直播',
  'app.live.room.yuyue':'我的预约',
  'app.live.room.num':'在线人数',
  'app.live.room.duration':'直播时长',
  'app.btn.contact':'立即预约',
  'app.title.myinvitation':'我收到的预约',
  'app.connect.label.invitaionSoon': '离线留言',
  'app.invitaion.dialog.theme':'预约主题',
  'app.invitaion.dialog.theme.placeholder':'请输入预约主题',
  'app.invitaion.dialog.date':'日期',
  'app.invitaion.dialog.date.placeholder':'选择日期',
  'app.invitaion.dialog.time.start':'开始时间',
  'app.invitaion.dialog.time.placeholder':'选择时间',
  'app.invitaion.dialog.time.end':'结束时间',
  'app.invitaion.dialog.msg':'留言',
  'app.invitaion.dialog.msg.placeholder':'请输入留言内容',
  'app.btn.sure':'确认',
  'app.btn.cancel':'取消',
  'app.info.choosed':'当前选择',
  'app.info.end': '结束',
  'app.pop.title.exitlive': '确认结束直播?',
}